// In development Next proxies this path to FastAPI. This avoids browser CORS/port issues.
export const API = process.env.NEXT_PUBLIC_API_URL || '/api';
export type Question = {id:string; type:string; title:string; description:string; required:boolean; options:string[]};
export type LogicRule = {sourceQuestionId:string; expectedValue:string; targetQuestionId:string};
export type Form = {id:string; title:string; slug:string; status:'draft'|'published'; settings:{theme?:string;thankYou?:string;logic?:LogicRule}; questions:Question[]; response_count:number; created_at:string; updated_at:string};
async function request(path:string, init?:RequestInit) { const r=await fetch(API+path,{cache:'no-store',headers:{'Content-Type':'application/json'},...init}); if(!r.ok) { const payload=await r.json().catch(()=>({detail:'Request failed'})); const detail=payload.detail; throw new Error(typeof detail==='string'?detail:detail&&typeof detail==='object'?Object.values(detail).join(' '):'Request failed'); } return r.json(); }
export const api = { forms:()=>request('/forms'), form:(id:string)=>request(`/forms/${id}`), create:(body:Partial<Form>)=>request('/forms',{method:'POST',body:JSON.stringify(body)}), update:(id:string,body:Partial<Form>)=>request(`/forms/${id}`,{method:'PUT',body:JSON.stringify(body)}), remove:(id:string)=>request(`/forms/${id}`,{method:'DELETE'}), duplicate:(id:string)=>request(`/forms/${id}/duplicate`,{method:'POST'}), publish:(id:string,published:boolean)=>request(`/forms/${id}/publish?published=${published}`,{method:'POST'}), responses:(id:string)=>request(`/forms/${id}/responses`), response:(formId:string,responseId:string)=>request(`/forms/${formId}/responses/${responseId}`), public:(slug:string)=>request(`/public/forms/${slug}`), submit:(slug:string,answers:Record<string,string>)=>request(`/public/forms/${slug}/responses`,{method:'POST',body:JSON.stringify({answers})}) };
export const questionTypes = [{type:'short_text',name:'Short text',icon:'T'},{type:'long_text',name:'Long text',icon:'Ã‚Â¶'},{type:'multiple_choice',name:'Multiple choice',icon:'Ã¢â€”â€°'},{type:'dropdown',name:'Dropdown',icon:'Ã¢Å’â€ž'},{type:'email',name:'Email',icon:'@'},{type:'number',name:'Number',icon:'#'},{type:'yes_no',name:'Yes / No',icon:'Ã¢Å“â€œ'},{type:'rating',name:'Rating',icon:'Ã¢Ëœâ€¦'}];
export const newQuestion=(type='short_text'):Question=>({id:crypto.randomUUID(),type,title:'Untitled question',description:'',required:false,options:type==='multiple_choice'?['Option 1','Option 2']:type==='dropdown'?['Option 1','Option 2']:type==='rating'?['1','2','3','4','5']:[]});




